apps/projects/urls.py
from django.urls import path

from apps.projects import views

app_name = 'projects'

urlpatterns = [
    path('project/list/', views.ProjectListView.as_view(), name='project-list'),
    path('project/create/', views.ProjectCreateView.as_view(), name='project-create'),
    path('project/delete/<int:pk>/', views.ProjectDelete.as_view(), name='project-delete'),
    path('project/update/<int:pk>/', views.ProjectUpdate.as_view(), name='project-update'),
]

atlas/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import IndexView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', IndexView.as_view(), name='index'),
    path('projects/', include('apps.projects.urls', namespace='projects')),
]

apps/projects/models.py
from django.db import models


# Create your models here.

class Project(models.Model):
    name = models.CharField(max_length=32, verbose_name="项目名")


class Module(models.Model):
    name = models.CharField(max_length=32, verbose_name="模块名")
    description = models.TextField(verbose_name="描述")
    port = models.IntegerField(verbose_name="端口", blank=True, null=True)
    charger = models.CharField(default="", max_length=64, blank=True, verbose_name="负责人")
    package_name = models.CharField(max_length=32, blank=True, null=True, verbose_name="包名")
    project = models.ForeignKey(Project, on_delete="CASCADE")

apps/projects/forms.py
from django import forms

from apps.projects.models import Module


class ProjectForm(forms.ModelForm):
    class Meta:
        model = Module
        fields = '__all__'

apps/projects/views.py
from django.shortcuts import render
from django.views.generic import ListView, TemplateView, CreateView, DeleteView, UpdateView
from django.urls import reverse_lazy
from django.contrib import messages

from apps.projects.models import Module
from apps.projects.forms import ProjectForm




# Create your views here.


class ProjectListView(ListView):
    model = Module
    template_name = 'project/list.html'
    context_object_name = 'project_obj'



class ProjectCreateView(CreateView):
    model = Module
    form_class = ProjectForm
    template_name = 'project/create.html'
    context_object_name = 'project_obj'
    success_url = reverse_lazy('projects:project-list')


class ProjectDelete(DeleteView):
    model = Module
    template_name = 'project/delete.html'
    context_object_name = 'project_obj'
    success_url = reverse_lazy('projects:project-list')


class ProjectUpdate(UpdateView):
    model = Module
    form_class = ProjectForm
    template_name = 'project/update.html'
    context_object_name = 'project_obj'
    success_url = reverse_lazy('projects:project-list')





















    

atlas/views.py
from django.views.generic import TemplateView


class IndexView(TemplateView):
    template_name = 'base/_base.html'
    # template_name = 'index.html'

apps/projects/templates/project/create.html
{% extends "base/_base.html" %}
{% load static %}
{% block content %}
    <section class="content">
        <div class="container-fluid">
            <div class="block-header">
                <h2>添加项目</h2>
            </div>

            <!-- Horizontal Layout -->
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2>
                                添加项目
                            </h2>
                            <ul class="header-dropdown m-r--5">
                                <li class="dropdown">
                                    <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                        <i class="material-icons">more_vert</i>
                                    </a>
                                    <ul class="dropdown-menu pull-right">
                                        <li><a href="javascript:void(0);">Action</a></li>
                                        <li><a href="javascript:void(0);">Another action</a></li>
                                        <li><a href="javascript:void(0);">Something else here</a></li>
                                    </ul>
                                </li>
                            </ul>
                        </div>
                        <div class="body">
                            <form class="form-horizontal" method="post">
                                {% csrf_token %}
                                <div class="row clearfix">
                                    <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                        <label for="name">模块名</label>
                                    </div>
                                    <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                        <div class="form-group">
                                            <div class="form-line">
                                                <input type="text" id="name" name="name" class="form-control">
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row clearfix">
                                    <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                        <label for="description">描述</label>
                                    </div>
                                    <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                        <div class="form-group">
                                            <div class="form-line">
                                                <input type="text" id="description" name="description" class="form-control">
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row clearfix">
                                    <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                        <label for="port">端口</label>
                                    </div>
                                    <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                        <div class="form-group">
                                            <div class="form-line">
                                                <input type="text" id="port" name="port" class="form-control">
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row clearfix">
                                    <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                        <label for="package_name">包名</label>
                                    </div>
                                    <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                        <div class="form-group">
                                            <div class="form-line">
                                                <input type="text" id="package_name" name="package_name" class="form-control">
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row clearfix">
                                    <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                        <label for="charger">负责人</label>
                                    </div>
                                    <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                        <div class="form-group">
                                            <div class="form-line">
                                                <input type="text" id="charger" name="charger" class="form-control">
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row clearfix">
                                    <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                        <label for="project_name">项目名</label>
                                    </div>
                                    <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                        <div class="form-group">
                                            <div class="form-line">
                                                <input type="text" id="project_name" name="project_name" class="form-control">
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row clearfix">
                                    <div class="col-lg-offset-2 col-md-offset-2 col-sm-offset-4 col-xs-offset-5">
                                        <button type="submit" class="btn btn-primary m-t-15 waves-effect">提交</button>
                                        <a type="button" href="{% url 'projects:project-list' %}" class="btn btn-info m-t-15 waves-effect">返回</a>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <!-- #END# Horizontal Layout -->
        </div>
    </section>
{% endblock %}

apps/projects/templates/project/delete.html
<form method="post">{% csrf_token %}
    <p>确定要删除 "{{ object.project_name }}项目的{{ object.name }}应用"?</p>
    <input type="submit" value="确定">
</form>

apps/projects/templates/project/list.html
{% extends "base/_base.html" %}
{% load static %}
{% block content %}
    <section class="content">
        <div class="container-fluid">
            <div class="block-header">
                <h2>模块列表</h2>
            </div>

            <!-- Striped Rows -->
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2>
                                模块列表
                            </h2>
                            <ul class="header-dropdown m-r--5">
                                <li class="dropdown">
                                    <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                        <i class="material-icons">more_vert</i>
                                    </a>
                                    <ul class="dropdown-menu pull-right">
                                        <li><a href="{% url 'projects:project-create' %}">添加</a></li>                                                                                                								
                                    </ul>
                                </li>
                            </ul>
                        </div>
                        <div class="body table-responsive">
                            <table class="table table-striped">
                                <thead>
                                    <tr>
                                        <th>模块名</th>
                                        <th>描述</th>
                                        <th>端口</th>
                                        <th>负责人</th>
                                        <th>包名</th>
                                        <th>项目名</th>
										<th>操作</th>
                                    </tr>
                                </thead>								      
                                <tbody>	
                                        {% for project in project_obj %}
                                    <tr>									    
                                        <td>{{project.name}}</a></td>
                                        <td>{{project.description}}</td>
                                        <td>{{project.port}}</td>
                                        <td>{{project.charger}}</td>
                                        <td>{{project.package_name}}</td>
                                        <td>{{project.project_name}}</td>
										<td><a href="{% url 'projects:project-update' pk=project.id %}">编辑</a>  <a href="{% url 'projects:project-delete' pk=project.id %}">删除</a></td>
                                    </tr>
                                         {% endfor %}									
                                </tbody>								    
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <!-- #END# Striped Rows -->
        </div>
    </section>
{% endblock %}

apps/projects/templates/project/update.html
{% extends "base/_base.html" %}
{% load static %}
{% block content %}
    <section class="content">
        <div class="container-fluid">
            <div class="block-header">
                <h2>编辑项目</h2>
            </div>

            <!-- Horizontal Layout -->
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2>
                                编辑项目
                            </h2>
                            <ul class="header-dropdown m-r--5">
                                <li class="dropdown">
                                    <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                        <i class="material-icons">more_vert</i>
                                    </a>
                                    <ul class="dropdown-menu pull-right">
                                        <li><a href="javascript:void(0);">Action</a></li>
                                        <li><a href="javascript:void(0);">Another action</a></li>
                                        <li><a href="javascript:void(0);">Something else here</a></li>
                                    </ul>
                                </li>
                            </ul>
                        </div>
                        <div class="body">
                            <form class="form-horizontal" method="post">
                                {% csrf_token %}							
                                <div class="row clearfix">
                                    <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label" >
                                        <label for="name">模块名</label>
                                    </div>
                                    <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7" >									    
                                        <div class="form-group" >
                                            <div  class="form-line" >											     
                                                <input type="text" id="name" value="{{ object.name }}" name="name" class="form-control">                                                												
                                            </div>											
                                        </div>
                                    </div>
                                </div>
                                <div class="row clearfix">
                                    <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                        <label for="description">描述</label>
                                    </div>
                                    <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                        <div class="form-group">
                                            <div class="form-line">
                                                <input type="text" id="description" value="{{ object.description }}" name="description" class="form-control">												
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row clearfix">
                                    <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                        <label for="port">端口</label>
                                    </div>
                                    <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                        <div class="form-group">
                                            <div class="form-line">
                                                <input type="text" id="port" value="{{ object.port }}" name="port" class="form-control">												
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row clearfix">
                                    <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                        <label for="package_name">包名</label>
                                    </div>
                                    <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                        <div class="form-group">
                                            <div class="form-line">
                                                <input type="text" id="package_name" value="{{ object.package_name }}" name="package_name" class="form-control">
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row clearfix">
                                    <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                        <label for="charger">负责人</label>
                                    </div>
                                    <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                        <div class="form-group">
                                            <div class="form-line">
                                                <input type="text" id="charger" value="{{ object.charger }}" name="charger" class="form-control"> 												
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row clearfix">
                                    <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                        <label for="project_name">项目名</label>
                                    </div>
                                    <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                        <div class="form-group">
                                            <div class="form-line">
                                                <input type="text" id="project_name" value="{{ object.project_name }}" name="project_name" class="form-control"> 												
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row clearfix">
                                    <div class="col-lg-offset-2 col-md-offset-2 col-sm-offset-4 col-xs-offset-5">
                                        <button type="submit" class="btn btn-primary m-t-15 waves-effect">提交</button>
                                        <a type="button" href="{% url 'projects:project-list' %}" class="btn btn-info m-t-15 waves-effect">返回</a>
                                    </div>
                                </div>								
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <!-- #END# Horizontal Layout -->
        </div>
    </section>
{% endblock %}

templates/base/_css.html
{% load static %}
<!-- Google Fonts -->
<link rel="stylesheet" href={% static "plugins/googleapis/fonts.css" %} >
<link rel="stylesheet" href={% static "plugins/googleapis/icons.css" %} >
<!-- Bootstrap Core Css -->
<link rel="stylesheet" href={% static "plugins/bootstrap/css/bootstrap.css" %} />
<!-- Waves Effect Css -->
<link rel="stylesheet" href={% static "plugins/node-waves/waves.css" %} />
<!-- Animation Css -->
<link rel="stylesheet" href={% static "plugins/animate-css/animate.css" %} />
<!-- Custom Css -->
<link rel="stylesheet" href={% static "css/style.css" %} >
<!-- AdminBSB Themes -->
<link rel="stylesheet" href={% static "css/themes/all-themes.css" %} />

templates/base/_js.html
{% load static %}
<!-- Jquery Core Js -->
<script src={% static "plugins/jquery/jquery.min.js" %}></script>
<!-- Bootstrap Core Js -->
<script src={% static "plugins/bootstrap/js/bootstrap.js" %}></script>
<!-- Waves Effect Plugin Js -->
<script src={% static "plugins/node-waves/waves.js" %}></script>
<!-- Jquery CountTo Plugin Js -->
<script src={% static "plugins/jquery-countto/jquery.countTo.js" %}></script>
<!-- Slimscroll Plugin Js -->
<script src={% static "plugins/jquery-slimscroll/jquery.slimscroll.js" %}></script>
<!-- Custom Js -->
<script src={% static "js/admin.js" %}></script>
<script src={% static "js/pages/index.js" %}></script>
<!-- Demo Js -->
<script src={% static "js/demo.js" %}></script>